const fs = require('fs');
const path = require('path');

const filePath = path.join('c:', 'Users', 'paksh', 'OneDrive', 'Desktop', 'Resume Forge', 'frontend', 'lib', 'templates.ts');
let content = fs.readFileSync(filePath, 'utf8');

const newTemplates = {
  'avatar-pro': { name: 'Avatar Pro', category: 'Executive Style', accent: '#1f2937', thumbnail: 'single-column',
    html: `<div class="av-page"><header class="av-header"><div class="av-header-inner">{{profileImage}}<div class="av-header-text"><h1 class="av-name">{{name}}</h1><div class="av-contact"><span>{{email}}</span><span>{{phone}}</span><span>{{location}}</span></div></div></div></header><div class="av-body"><section class="av-sec"><h2 class="av-h2">Profile</h2><p class="av-p">{{summary}}</p></section><section class="av-sec"><h2 class="av-h2">Experience</h2>{{experience}}</section><div class="av-two"><div><h2 class="av-h2">Education</h2>{{education}}</div><div><h2 class="av-h2">Skills</h2>{{skills}}</div></div><section class="av-sec"><h2 class="av-h2" style="margin-top:20px">Projects</h2>{{projects}}</section></div></div>`,
    css: `.av-page{font-family:var(--font-family);background:#fff;font-size:var(--base-font-size);min-height:1130px;}.av-header{padding:48px 56px 32px;background:#f9fafb;border-bottom:1px solid #e5e7eb;}.av-header-inner{display:flex;flex-direction:var(--header-flex-dir);align-items:var(--header-align-items);text-align:var(--image-text-align);gap:28px;}.profile-img{width:110px;height:110px;border-radius:var(--image-radius);background-size:cover;background-position:center;flex-shrink:0;box-shadow:0 4px 12px rgba(0,0,0,0.08);}.profile-img.fallback{background:var(--primary-color);color:#fff;display:flex;align-items:center;justify-content:center;font-size:36px;font-weight:bold;}.av-name{font-size:2.8em;font-weight:800;color:#111827;margin:0 0 8px;letter-spacing:-0.5px;}.av-contact{display:flex;gap:16px;flex-wrap:wrap;justify-content:inherit;}.av-contact span{font-size:0.85em;color:#4b5563;font-weight:500;}.av-body{padding:36px 56px;}.av-two{display:grid;grid-template-columns:1fr 1fr;gap:32px;}.av-sec{margin-bottom:28px;}.av-h2{font-size:0.85em;font-weight:800;color:var(--primary-color);letter-spacing:1.5px;text-transform:uppercase;border-bottom:2px solid #e5e7eb;padding-bottom:6px;margin:0 0 16px;}.av-p{font-size:0.95em;color:#374151;line-height:1.7;}.card-side{display:none;}.work-card{margin-bottom:20px;}.card-header{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:4px;}.position{font-size:1.05em;font-weight:700;color:#111827;}.company{font-size:0.9em;color:var(--primary-color);font-weight:600;margin-bottom:8px;}.date{font-size:0.85em;color:#6b7280;font-weight:500;}.summary{font-size:0.9em;color:#4b5563;line-height:1.65;}.skill-row{display:flex;align-items:center;margin-bottom:8px;}.skill-meta{width:120px;font-size:0.85em;font-weight:600;color:#374151;}.skill-track{flex:1;height:6px;background:#e5e7eb;border-radius:3px;overflow:hidden;margin-left:12px;}.skill-fill{height:100%;background:var(--primary-color);}.skill-val{display:none;}.edu-card{margin-bottom:16px;}.edu-info .area{font-size:0.95em;font-weight:700;color:#111827;}.edu-info .institution{font-size:0.85em;color:#4b5563;margin-top:2px;}.edu-date{font-size:0.8em;color:#6b7280;display:block;margin-top:4px;}.project-card{margin-bottom:16px;}.project-name{font-size:0.95em;font-weight:700;color:#111827;}.project-desc{font-size:0.88em;color:#4b5563;margin-top:4px;line-height:1.6;}`
  },

  'profile-wave': { name: 'Profile Wave', category: 'Creative Style', accent: '#4f46e5', thumbnail: 'single-column',
    html: `<div class="wv-page"><div class="wv-hero"><div class="wv-hero-inner">{{profileImage}}<div class="wv-hero-text"><h1 class="wv-name">{{name}}</h1><p class="wv-contact">{{email}} | {{phone}} | {{location}}</p></div></div><svg class="wv-svg" viewBox="0 0 1440 120" preserveAspectRatio="none"><path fill="#ffffff" d="M0,64L80,69.3C160,75,320,85,480,80C640,75,800,53,960,48C1120,43,1280,53,1360,58.7L1440,64L1440,120L1360,120C1280,120,1120,120,960,120C800,120,640,120,480,120C320,120,160,120,80,120L0,120Z"></path></svg></div><div class="wv-body"><section class="wv-sec full"><h2 class="wv-h2">About Me</h2><p class="wv-p">{{summary}}</p></section><div class="wv-grid"><div class="wv-main"><section class="wv-sec"><h2 class="wv-h2">Experience</h2>{{experience}}</section><section class="wv-sec"><h2 class="wv-h2">Projects</h2>{{projects}}</section></div><div class="wv-side"><section class="wv-sec"><h2 class="wv-h2">Education</h2>{{education}}</section><section class="wv-sec"><h2 class="wv-h2">Skills</h2>{{skills}}</section></div></div></div></div>`,
    css: `.wv-page{font-family:var(--font-family);background:#fff;font-size:var(--base-font-size);min-height:1130px;}.wv-hero{background:linear-gradient(135deg,var(--primary-color),#312e81);padding:48px 56px 0;position:relative;color:#fff;}.wv-hero-inner{display:flex;flex-direction:var(--header-flex-dir);align-items:var(--header-align-items);text-align:var(--image-text-align);gap:24px;position:relative;z-index:2;padding-bottom:32px;}.profile-img{width:120px;height:120px;border-radius:var(--image-radius);background-size:cover;background-position:center;border:4px solid rgba(255,255,255,0.3);flex-shrink:0;}.profile-img.fallback{background:rgba(255,255,255,0.2);color:#fff;display:flex;align-items:center;justify-content:center;font-size:40px;font-weight:bold;}.wv-name{font-size:3em;font-weight:900;margin:0 0 8px;letter-spacing:-1px;}.wv-contact{font-size:0.9em;opacity:0.9;margin:0;font-weight:500;}.wv-svg{position:absolute;bottom:0;left:0;width:100%;height:40px;display:block;}.wv-body{padding:24px 56px 48px;}.wv-grid{display:grid;grid-template-columns:1fr var(--sidebar-width);gap:40px;}.wv-sec{margin-bottom:28px;}.wv-h2{font-size:1.1em;font-weight:800;color:#111827;margin:0 0 16px;position:relative;display:inline-block;}.wv-h2::after{content:'';position:absolute;bottom:-4px;left:0;width:40px;height:4px;background:var(--primary-color);border-radius:2px;}.wv-p{font-size:0.95em;color:#4b5563;line-height:1.7;}.card-side{display:none;}.work-card{margin-bottom:24px;}.card-header{margin-bottom:6px;}.position{font-size:1.05em;font-weight:800;color:#111827;}.company{font-size:0.9em;color:var(--primary-color);font-weight:700;display:inline-block;margin-right:12px;}.date{font-size:0.85em;color:#6b7280;background:#f3f4f6;padding:2px 8px;border-radius:12px;font-weight:600;}.summary{font-size:0.9em;color:#4b5563;line-height:1.6;margin-top:8px;}.skill-row{margin-bottom:12px;}.skill-meta{display:flex;justify-content:space-between;font-size:0.85em;font-weight:700;color:#374151;margin-bottom:4px;}.skill-track{height:8px;background:#f3f4f6;border-radius:4px;overflow:hidden;}.skill-fill{height:100%;background:var(--primary-color);border-radius:4px;}.edu-card{margin-bottom:16px;padding-left:16px;border-left:2px solid #e5e7eb;}.edu-info .area{font-size:0.95em;font-weight:800;color:#111827;}.edu-info .institution{font-size:0.85em;color:var(--primary-color);font-weight:600;margin-top:2px;}.edu-date{font-size:0.8em;color:#6b7280;margin-top:4px;}.project-card{margin-bottom:16px;}.project-name{font-size:1em;font-weight:800;color:#111827;}.project-desc{font-size:0.9em;color:#4b5563;margin-top:4px;line-height:1.6;}`
  },

  'elegant-face': { name: 'Elegant Face', category: 'Executive Style', accent: '#0f172a', thumbnail: 'single-column',
    html: `<div class="ef-page"><div class="ef-sidebar"><div class="ef-profile">{{profileImage}}</div><h1 class="ef-name">{{name}}</h1><p class="ef-contact">{{email}}<br>{{phone}}<br>{{location}}</p><div class="ef-divider"></div><h2 class="ef-h2">Skills</h2><div class="ef-skills">{{skills}}</div><div class="ef-divider"></div><h2 class="ef-h2">Education</h2><div class="ef-edu">{{education}}</div></div><div class="ef-main"><section class="ef-sec"><h2 class="ef-h2-main">Executive Summary</h2><p class="ef-p">{{summary}}</p></section><section class="ef-sec"><h2 class="ef-h2-main">Professional Experience</h2>{{experience}}</section><section class="ef-sec"><h2 class="ef-h2-main">Projects</h2>{{projects}}</section></div></div>`,
    css: `.ef-page{font-family:var(--font-family);background:#fff;font-size:var(--base-font-size);min-height:1130px;display:flex;}.ef-sidebar{width:var(--sidebar-width);background:#f8fafc;padding:48px 32px;border-right:1px solid #e2e8f0;}.ef-profile{display:flex;justify-content:center;margin-bottom:24px;}.profile-img{width:140px;height:140px;border-radius:var(--image-radius);background-size:cover;background-position:center;border:1px solid #cbd5e1;box-shadow:0 10px 15px -3px rgba(0,0,0,0.1);}.profile-img.fallback{background:var(--primary-color);color:#fff;display:flex;align-items:center;justify-content:center;font-size:48px;font-weight:300;}.ef-name{font-size:2.2em;font-weight:300;color:#0f172a;text-align:center;margin:0 0 16px;line-height:1.2;}.ef-contact{font-size:0.85em;color:#475569;text-align:center;line-height:1.8;}.ef-divider{height:1px;background:#cbd5e1;margin:24px 0;}.ef-h2{font-size:0.8em;font-weight:700;color:var(--primary-color);letter-spacing:2px;text-transform:uppercase;margin:0 0 16px;text-align:center;}.ef-skills .skill-row{margin-bottom:12px;}.ef-skills .skill-meta{display:flex;justify-content:space-between;font-size:0.8em;font-weight:600;color:#334155;margin-bottom:4px;}.ef-skills .skill-track{height:4px;background:#e2e8f0;border-radius:2px;}.ef-skills .skill-fill{height:100%;background:var(--primary-color);}.ef-edu .edu-card{margin-bottom:16px;text-align:center;}.ef-edu .area{font-size:0.9em;font-weight:700;color:#0f172a;}.ef-edu .institution{font-size:0.8em;color:#475569;margin-top:2px;}.ef-edu .edu-date{font-size:0.75em;color:#64748b;margin-top:2px;}.ef-main{flex:1;padding:48px 56px;}.ef-sec{margin-bottom:36px;}.ef-h2-main{font-size:1.4em;font-weight:300;color:var(--primary-color);border-bottom:1px solid #cbd5e1;padding-bottom:8px;margin:0 0 20px;}.ef-p{font-size:0.95em;color:#334155;line-height:1.8;}.card-side{display:none;}.work-card{margin-bottom:28px;}.card-header{margin-bottom:6px;}.position{font-size:1.1em;font-weight:600;color:#0f172a;}.company{font-size:0.95em;color:var(--primary-color);font-weight:500;display:block;margin-bottom:4px;}.date{font-size:0.85em;color:#64748b;font-style:italic;}.summary{font-size:0.95em;color:#334155;line-height:1.7;margin-top:8px;}.project-card{margin-bottom:20px;}.project-name{font-size:1.05em;font-weight:600;color:#0f172a;}.project-desc{font-size:0.9em;color:#334155;margin-top:4px;line-height:1.7;}`
  },

  'modern-split': { name: 'Modern Split', category: 'Modern Style', accent: '#059669', thumbnail: 'single-column',
    html: `<div class="ms-page"><header class="ms-header"><div class="ms-inner">{{profileImage}}<div class="ms-text"><h1 class="ms-name">{{name}}</h1><h2 class="ms-title">{{email}} • {{phone}} • {{location}}</h2></div></div></header><div class="ms-body"><div class="ms-col1"><section class="ms-sec"><h3 class="ms-h3">Profile</h3><p class="ms-p">{{summary}}</p></section><section class="ms-sec"><h3 class="ms-h3">Skills</h3><div class="ms-skills">{{skills}}</div></section><section class="ms-sec"><h3 class="ms-h3">Education</h3>{{education}}</section></div><div class="ms-col2"><section class="ms-sec"><h3 class="ms-h3">Experience</h3>{{experience}}</section><section class="ms-sec"><h3 class="ms-h3">Projects</h3>{{projects}}</section></div></div></div>`,
    css: `.ms-page{font-family:var(--font-family);background:#fff;font-size:var(--base-font-size);min-height:1130px;}.ms-header{background:#111827;color:#fff;padding:48px 56px;}.ms-inner{display:flex;flex-direction:var(--header-flex-dir);align-items:var(--header-align-items);text-align:var(--image-text-align);gap:32px;}.profile-img{width:96px;height:96px;border-radius:var(--image-radius);background-size:cover;background-position:center;border:2px solid var(--primary-color);flex-shrink:0;}.profile-img.fallback{background:var(--primary-color);color:#fff;display:flex;align-items:center;justify-content:center;font-size:32px;font-weight:bold;}.ms-name{font-size:2.8em;font-weight:800;margin:0 0 8px;letter-spacing:-1px;}.ms-title{font-size:0.95em;font-weight:400;color:#9ca3af;margin:0;letter-spacing:1px;}.ms-body{display:grid;grid-template-columns:30% 1fr;gap:48px;padding:48px 56px;}.ms-sec{margin-bottom:32px;}.ms-h3{font-size:1em;font-weight:800;color:#111827;text-transform:uppercase;letter-spacing:1px;margin:0 0 16px;display:flex;align-items:center;gap:12px;}.ms-h3::after{content:'';flex:1;height:1px;background:#e5e7eb;}.ms-p{font-size:0.9em;color:#4b5563;line-height:1.7;}.ms-skills .skill-row{margin-bottom:12px;}.ms-skills .skill-meta{font-size:0.85em;font-weight:700;color:#374151;margin-bottom:4px;display:flex;justify-content:space-between;}.ms-skills .skill-track{height:6px;background:#f3f4f6;border-radius:3px;}.ms-skills .skill-fill{height:100%;background:var(--primary-color);border-radius:3px;}.edu-card{margin-bottom:16px;}.edu-info .area{font-size:0.9em;font-weight:700;color:#111827;}.edu-info .institution{font-size:0.85em;color:#6b7280;margin-top:2px;}.edu-date{font-size:0.8em;color:var(--primary-color);font-weight:600;margin-top:4px;display:block;}.card-side{display:none;}.work-card{margin-bottom:28px;}.card-header{margin-bottom:4px;}.position{font-size:1.1em;font-weight:700;color:#111827;}.company{font-size:0.95em;color:var(--primary-color);font-weight:600;}.date{font-size:0.85em;color:#6b7280;float:right;font-weight:500;}.summary{font-size:0.9em;color:#4b5563;line-height:1.7;margin-top:8px;clear:both;}.project-card{margin-bottom:20px;}.project-name{font-size:1.05em;font-weight:700;color:#111827;}.project-desc{font-size:0.9em;color:#4b5563;line-height:1.6;margin-top:4px;}`
  },

  'clean-focus': { name: 'Clean Focus', category: 'Minimalist Style', accent: '#2563eb', thumbnail: 'single-column',
    html: `<div class="cf-page"><header class="cf-header"><div class="cf-header-inner">{{profileImage}}<div class="cf-header-text"><h1 class="cf-name">{{name}}</h1><p class="cf-contact">{{email}} | {{phone}} | {{location}}</p></div></div></header><div class="cf-body"><section class="cf-sec"><h2 class="cf-h2">Summary</h2><p class="cf-p">{{summary}}</p></section><div class="cf-grid"><div class="cf-left"><section class="cf-sec"><h2 class="cf-h2">Experience</h2>{{experience}}</section><section class="cf-sec"><h2 class="cf-h2">Projects</h2>{{projects}}</section></div><div class="cf-right"><section class="cf-sec"><h2 class="cf-h2">Education</h2>{{education}}</section><section class="cf-sec"><h2 class="cf-h2">Skills</h2>{{skills}}</section></div></div></div></div>`,
    css: `.cf-page{font-family:var(--font-family);background:#fff;font-size:var(--base-font-size);min-height:1130px;}.cf-header{padding:48px 56px 24px;border-bottom:2px solid #f3f4f6;}.cf-header-inner{display:flex;flex-direction:var(--header-flex-dir);align-items:var(--header-align-items);text-align:var(--image-text-align);gap:24px;}.profile-img{width:80px;height:80px;border-radius:var(--image-radius);background-size:cover;background-position:center;flex-shrink:0;}.profile-img.fallback{background:var(--primary-color);color:#fff;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:600;}.cf-name{font-size:2.4em;font-weight:700;color:#111827;margin:0 0 8px;letter-spacing:-0.5px;}.cf-contact{font-size:0.9em;color:#6b7280;margin:0;}.cf-body{padding:32px 56px;}.cf-sec{margin-bottom:28px;}.cf-h2{font-size:0.9em;font-weight:700;color:#111827;text-transform:uppercase;letter-spacing:1px;margin:0 0 16px;color:var(--primary-color);}.cf-p{font-size:0.95em;color:#374151;line-height:1.7;}.cf-grid{display:grid;grid-template-columns:1fr var(--sidebar-width);gap:40px;}.card-side{display:none;}.work-card{margin-bottom:24px;}.card-header{margin-bottom:4px;}.position{font-size:1.05em;font-weight:600;color:#111827;}.company{font-size:0.9em;color:#4b5563;font-weight:500;}.date{font-size:0.85em;color:#9ca3af;float:right;}.summary{font-size:0.95em;color:#374151;line-height:1.6;margin-top:8px;clear:both;}.edu-card{margin-bottom:16px;}.edu-info .area{font-size:0.95em;font-weight:600;color:#111827;}.edu-info .institution{font-size:0.85em;color:#6b7280;margin-top:2px;}.edu-date{font-size:0.8em;color:#9ca3af;display:block;margin-top:2px;}.skill-row{display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:1px solid #f3f4f6;}.skill-meta{font-size:0.9em;font-weight:500;color:#374151;}.skill-val{font-size:0.8em;color:var(--primary-color);font-weight:600;}.skill-track,.skill-fill{display:none;}.project-card{margin-bottom:20px;}.project-name{font-size:1em;font-weight:600;color:#111827;}.project-desc{font-size:0.9em;color:#4b5563;line-height:1.6;margin-top:4px;}`
  },

  'bold-vision': { name: 'Bold Vision', category: 'Creative Style', accent: '#dc2626', thumbnail: 'single-column',
    html: `<div class="bv-page"><div class="bv-sidebar"><div class="bv-profile-wrapper">{{profileImage}}</div><h2 class="bv-h2-side">Contact</h2><p class="bv-contact-item">{{email}}</p><p class="bv-contact-item">{{phone}}</p><p class="bv-contact-item">{{location}}</p><h2 class="bv-h2-side">Skills</h2><div class="bv-skills">{{skills}}</div></div><div class="bv-main"><header class="bv-header"><h1 class="bv-name">{{name}}</h1></header><section class="bv-sec"><h2 class="bv-h2">About</h2><p class="bv-p">{{summary}}</p></section><section class="bv-sec"><h2 class="bv-h2">Experience</h2>{{experience}}</section><section class="bv-sec"><h2 class="bv-h2">Education</h2>{{education}}</section></div></div>`,
    css: `.bv-page{font-family:var(--font-family);background:#fff;font-size:var(--base-font-size);min-height:1130px;display:flex;}.bv-sidebar{width:var(--sidebar-width);background:var(--primary-color);color:#fff;padding:48px 32px;}.bv-profile-wrapper{display:flex;justify-content:center;margin-bottom:40px;}.profile-img{width:130px;height:130px;border-radius:var(--image-radius);background-size:cover;background-position:center;border:4px solid rgba(255,255,255,0.2);}.profile-img.fallback{background:#fff;color:var(--primary-color);display:flex;align-items:center;justify-content:center;font-size:48px;font-weight:900;}.bv-h2-side{font-size:1.1em;font-weight:800;margin:0 0 16px;text-transform:uppercase;letter-spacing:1px;border-bottom:2px solid rgba(255,255,255,0.2);padding-bottom:8px;}.bv-contact-item{font-size:0.85em;margin:0 0 12px;opacity:0.9;}.bv-skills .skill-row{margin-bottom:12px;}.bv-skills .skill-meta{font-size:0.85em;font-weight:600;margin-bottom:4px;display:flex;justify-content:space-between;}.bv-skills .skill-track{height:6px;background:rgba(255,255,255,0.2);border-radius:3px;}.bv-skills .skill-fill{height:100%;background:#fff;border-radius:3px;}.bv-main{flex:1;padding:48px 56px;}.bv-header{margin-bottom:40px;}.bv-name{font-size:3.5em;font-weight:900;color:#111827;margin:0;line-height:1.1;letter-spacing:-1px;}.bv-sec{margin-bottom:36px;}.bv-h2{font-size:1.4em;font-weight:800;color:#111827;margin:0 0 20px;display:flex;align-items:center;gap:16px;}.bv-h2::after{content:'';flex:1;height:2px;background:#f3f4f6;}.bv-p{font-size:0.95em;color:#4b5563;line-height:1.8;}.card-side{display:none;}.work-card{margin-bottom:28px;}.card-header{margin-bottom:6px;}.position{font-size:1.15em;font-weight:800;color:#111827;}.company{font-size:0.95em;color:var(--primary-color);font-weight:700;}.date{font-size:0.85em;color:#6b7280;float:right;font-weight:600;}.summary{font-size:0.95em;color:#4b5563;line-height:1.7;margin-top:8px;clear:both;}.edu-card{margin-bottom:20px;}.edu-info .area{font-size:1.05em;font-weight:800;color:#111827;}.edu-info .institution{font-size:0.9em;color:#6b7280;margin-top:4px;}.edu-date{font-size:0.85em;color:var(--primary-color);font-weight:700;display:block;margin-top:4px;}`
  },

  'tech-squad': { name: 'Tech Squad', category: 'Tech Style', accent: '#8b5cf6', thumbnail: 'single-column',
    html: `<div class="ts-page"><header class="ts-header"><div class="ts-header-inner">{{profileImage}}<div class="ts-header-text"><h1 class="ts-name">{{name}}</h1><div class="ts-contact"><span class="ts-badge">{{email}}</span><span class="ts-badge">{{phone}}</span><span class="ts-badge">{{location}}</span></div></div></div></header><div class="ts-body"><div class="ts-col1"><section class="ts-sec"><h2 class="ts-h2">About</h2><p class="ts-p">{{summary}}</p></section><section class="ts-sec"><h2 class="ts-h2">Experience</h2>{{experience}}</section></div><div class="ts-col2"><section class="ts-sec"><h2 class="ts-h2">Skills</h2><div class="ts-skills">{{skills}}</div></section><section class="ts-sec"><h2 class="ts-h2">Projects</h2>{{projects}}</section><section class="ts-sec"><h2 class="ts-h2">Education</h2>{{education}}</section></div></div></div>`,
    css: `.ts-page{font-family:var(--font-family);background:#f8fafc;font-size:var(--base-font-size);min-height:1130px;}.ts-header{background:#fff;padding:40px 56px;border-bottom:1px solid #e2e8f0;}.ts-header-inner{display:flex;flex-direction:var(--header-flex-dir);align-items:var(--header-align-items);text-align:var(--image-text-align);gap:28px;}.profile-img{width:100px;height:100px;border-radius:var(--image-radius);background-size:cover;background-position:center;border:3px solid var(--primary-color);padding:3px;background-clip:content-box;flex-shrink:0;}.profile-img.fallback{background:var(--primary-color);color:#fff;display:flex;align-items:center;justify-content:center;font-size:36px;font-weight:700;}.ts-name{font-size:2.5em;font-weight:800;color:#0f172a;margin:0 0 12px;letter-spacing:-0.5px;}.ts-contact{display:flex;gap:8px;flex-wrap:wrap;justify-content:inherit;}.ts-badge{font-size:0.8em;background:#f1f5f9;color:#475569;padding:4px 10px;border-radius:6px;font-weight:600;border:1px solid #e2e8f0;}.ts-body{display:grid;grid-template-columns:1fr var(--sidebar-width);gap:32px;padding:32px 56px;}.ts-sec{background:#fff;padding:24px;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,0.05);margin-bottom:24px;border:1px solid #e2e8f0;}.ts-h2{font-size:1em;font-weight:700;color:#0f172a;margin:0 0 16px;display:flex;align-items:center;gap:8px;}.ts-h2::before{content:'';width:12px;height:12px;background:var(--primary-color);border-radius:3px;}.ts-p{font-size:0.9em;color:#475569;line-height:1.7;}.card-side{display:none;}.work-card{margin-bottom:24px;padding-bottom:24px;border-bottom:1px solid #e2e8f0;}.work-card:last-child{margin-bottom:0;padding-bottom:0;border-bottom:none;}.card-header{margin-bottom:6px;}.position{font-size:1.05em;font-weight:700;color:#0f172a;}.company{font-size:0.9em;color:var(--primary-color);font-weight:600;}.date{font-size:0.8em;color:#64748b;float:right;background:#f1f5f9;padding:2px 8px;border-radius:4px;}.summary{font-size:0.9em;color:#475569;line-height:1.6;margin-top:12px;clear:both;}.ts-skills .skill-row{margin-bottom:12px;}.ts-skills .skill-meta{font-size:0.85em;font-weight:600;color:#334155;margin-bottom:6px;}.ts-skills .skill-track{height:8px;background:#f1f5f9;border-radius:4px;overflow:hidden;}.ts-skills .skill-fill{height:100%;background:var(--primary-color);}.project-card{margin-bottom:20px;}.project-name{font-size:0.95em;font-weight:700;color:#0f172a;}.project-desc{font-size:0.85em;color:#475569;line-height:1.6;margin-top:6px;}.edu-card{margin-bottom:16px;}.edu-info .area{font-size:0.9em;font-weight:700;color:#0f172a;}.edu-info .institution{font-size:0.85em;color:#475569;margin-top:2px;}.edu-date{font-size:0.8em;color:#64748b;display:block;margin-top:4px;}`
  },

  'gradient-shift': { name: 'Gradient Shift', category: 'Creative Style', accent: '#ec4899', thumbnail: 'single-column',
    html: `<div class="gs-page"><div class="gs-bg"></div><header class="gs-header"><div class="gs-header-inner">{{profileImage}}<div class="gs-header-text"><h1 class="gs-name">{{name}}</h1><p class="gs-contact">{{email}} • {{phone}} • {{location}}</p></div></div></header><div class="gs-body"><section class="gs-sec"><h2 class="gs-h2">About</h2><p class="gs-p">{{summary}}</p></section><div class="gs-grid"><div class="gs-main"><section class="gs-sec"><h2 class="gs-h2">Experience</h2>{{experience}}</section><section class="gs-sec"><h2 class="gs-h2">Projects</h2>{{projects}}</section></div><div class="gs-side"><section class="gs-sec"><h2 class="gs-h2">Skills</h2><div class="gs-skills">{{skills}}</div></section><section class="gs-sec"><h2 class="gs-h2">Education</h2>{{education}}</section></div></div></div></div>`,
    css: `.gs-page{font-family:var(--font-family);background:#fff;font-size:var(--base-font-size);min-height:1130px;position:relative;}.gs-bg{position:absolute;top:0;left:0;width:100%;height:300px;background:linear-gradient(135deg,var(--primary-color),#fb923c);opacity:0.1;z-index:0;}.gs-header{padding:56px 56px 32px;position:relative;z-index:1;}.gs-header-inner{display:flex;flex-direction:var(--header-flex-dir);align-items:var(--header-align-items);text-align:var(--image-text-align);gap:32px;}.profile-img{width:110px;height:110px;border-radius:var(--image-radius);background-size:cover;background-position:center;box-shadow:0 10px 25px -5px rgba(0,0,0,0.1);flex-shrink:0;}.profile-img.fallback{background:var(--primary-color);color:#fff;display:flex;align-items:center;justify-content:center;font-size:36px;font-weight:800;}.gs-name{font-size:3em;font-weight:900;color:#111827;margin:0 0 8px;letter-spacing:-1px;background:linear-gradient(90deg,var(--primary-color),#fb923c);-webkit-background-clip:text;-webkit-text-fill-color:transparent;}.gs-contact{font-size:0.95em;color:#4b5563;font-weight:500;margin:0;}.gs-body{padding:0 56px 48px;position:relative;z-index:1;}.gs-sec{margin-bottom:32px;}.gs-h2{font-size:1.1em;font-weight:800;color:#111827;margin:0 0 16px;display:inline-block;border-bottom:3px solid var(--primary-color);padding-bottom:4px;}.gs-p{font-size:0.95em;color:#4b5563;line-height:1.7;}.gs-grid{display:grid;grid-template-columns:1fr var(--sidebar-width);gap:48px;}.card-side{display:none;}.work-card{margin-bottom:28px;}.card-header{margin-bottom:6px;}.position{font-size:1.1em;font-weight:800;color:#111827;}.company{font-size:0.95em;color:var(--primary-color);font-weight:700;}.date{font-size:0.85em;color:#6b7280;float:right;font-weight:500;}.summary{font-size:0.95em;color:#4b5563;line-height:1.7;margin-top:8px;clear:both;}.gs-skills .skill-row{margin-bottom:14px;}.gs-skills .skill-meta{display:flex;justify-content:space-between;font-size:0.9em;font-weight:700;color:#374151;margin-bottom:6px;}.gs-skills .skill-track{height:6px;background:#f3f4f6;border-radius:3px;}.gs-skills .skill-fill{height:100%;background:linear-gradient(90deg,var(--primary-color),#fb923c);border-radius:3px;}.edu-card{margin-bottom:20px;}.edu-info .area{font-size:1em;font-weight:800;color:#111827;}.edu-info .institution{font-size:0.9em;color:#6b7280;margin-top:4px;}.edu-date{font-size:0.85em;color:var(--primary-color);font-weight:700;display:block;margin-top:4px;}.project-card{margin-bottom:24px;}.project-name{font-size:1.05em;font-weight:800;color:#111827;}.project-desc{font-size:0.95em;color:#4b5563;line-height:1.6;margin-top:6px;}`
  },

  'solid-base': { name: 'Solid Base', category: 'Executive Style', accent: '#3b82f6', thumbnail: 'single-column',
    html: `<div class="sb-page"><header class="sb-header"><div class="sb-inner">{{profileImage}}<div class="sb-text"><h1 class="sb-name">{{name}}</h1><p class="sb-contact">{{email}} | {{phone}} | {{location}}</p></div></div></header><div class="sb-body"><div class="sb-grid"><div class="sb-main"><section class="sb-sec"><h2 class="sb-h2">Professional Summary</h2><p class="sb-p">{{summary}}</p></section><section class="sb-sec"><h2 class="sb-h2">Experience</h2>{{experience}}</section></div><div class="sb-side"><section class="sb-sec"><h2 class="sb-h2">Skills</h2>{{skills}}</section><section class="sb-sec"><h2 class="sb-h2">Education</h2>{{education}}</section><section class="sb-sec"><h2 class="sb-h2">Projects</h2>{{projects}}</section></div></div></div></div>`,
    css: `.sb-page{font-family:var(--font-family);background:#fff;font-size:var(--base-font-size);min-height:1130px;}.sb-header{background:var(--primary-color);color:#fff;padding:48px 56px;}.sb-inner{display:flex;flex-direction:var(--header-flex-dir);align-items:var(--header-align-items);text-align:var(--image-text-align);gap:32px;}.profile-img{width:120px;height:120px;border-radius:var(--image-radius);background-size:cover;background-position:center;border:4px solid rgba(255,255,255,0.2);flex-shrink:0;}.profile-img.fallback{background:#fff;color:var(--primary-color);display:flex;align-items:center;justify-content:center;font-size:40px;font-weight:bold;}.sb-name{font-size:2.8em;font-weight:800;margin:0 0 12px;letter-spacing:-0.5px;}.sb-contact{font-size:0.95em;opacity:0.9;margin:0;font-weight:500;}.sb-body{padding:40px 56px;}.sb-grid{display:grid;grid-template-columns:1fr var(--sidebar-width);gap:48px;}.sb-sec{margin-bottom:32px;}.sb-h2{font-size:1.05em;font-weight:800;color:#1e293b;text-transform:uppercase;letter-spacing:1px;margin:0 0 16px;padding-bottom:8px;border-bottom:2px solid #e2e8f0;}.sb-p{font-size:0.95em;color:#475569;line-height:1.7;}.card-side{display:none;}.work-card{margin-bottom:28px;}.card-header{margin-bottom:6px;}.position{font-size:1.1em;font-weight:700;color:#1e293b;}.company{font-size:0.95em;color:var(--primary-color);font-weight:600;}.date{font-size:0.85em;color:#64748b;float:right;font-weight:500;}.summary{font-size:0.95em;color:#475569;line-height:1.6;margin-top:8px;clear:both;}.skill-row{display:flex;justify-content:space-between;align-items:center;padding:8px 0;border-bottom:1px solid #f1f5f9;}.skill-meta{font-size:0.9em;font-weight:600;color:#334155;}.skill-val{font-size:0.85em;color:var(--primary-color);font-weight:700;background:#eff6ff;padding:2px 8px;border-radius:12px;}.skill-track,.skill-fill{display:none;}.edu-card{margin-bottom:16px;}.edu-info .area{font-size:0.95em;font-weight:700;color:#1e293b;}.edu-info .institution{font-size:0.85em;color:#64748b;margin-top:4px;}.edu-date{font-size:0.8em;color:var(--primary-color);font-weight:600;display:block;margin-top:4px;}.project-card{margin-bottom:20px;}.project-name{font-size:1em;font-weight:700;color:#1e293b;}.project-desc{font-size:0.9em;color:#475569;line-height:1.6;margin-top:4px;}`
  },

  'golden-ratio': { name: 'Golden Ratio', category: 'Minimalist Style', accent: '#ca8a04', thumbnail: 'single-column',
    html: `<div class="gr-page"><div class="gr-header"><div class="gr-inner">{{profileImage}}<div class="gr-text"><h1 class="gr-name">{{name}}</h1><p class="gr-title">{{email}}</p><p class="gr-contact">{{phone}} • {{location}}</p></div></div></div><div class="gr-body"><section class="gr-sec"><h2 class="gr-h2">Profile</h2><p class="gr-p">{{summary}}</p></section><section class="gr-sec"><h2 class="gr-h2">Experience</h2>{{experience}}</section><div class="gr-grid"><div><h2 class="gr-h2">Education</h2>{{education}}</div><div><h2 class="gr-h2">Skills</h2><div class="gr-skills">{{skills}}</div></div></div></div></div>`,
    css: `.gr-page{font-family:var(--font-family);background:#fefce8;font-size:var(--base-font-size);min-height:1130px;color:#422006;}.gr-header{padding:48px 56px 32px;}.gr-inner{display:flex;flex-direction:var(--header-flex-dir);align-items:var(--header-align-items);text-align:var(--image-text-align);gap:32px;}.profile-img{width:100px;height:100px;border-radius:var(--image-radius);background-size:cover;background-position:center;border:2px solid var(--primary-color);flex-shrink:0;}.profile-img.fallback{background:var(--primary-color);color:#fff;display:flex;align-items:center;justify-content:center;font-size:32px;font-weight:600;}.gr-name{font-size:3em;font-weight:800;color:#713f12;margin:0 0 8px;letter-spacing:-1px;}.gr-title{font-size:1.1em;color:var(--primary-color);font-weight:600;margin:0 0 4px;}.gr-contact{font-size:0.9em;color:#854d0e;margin:0;}.gr-body{padding:0 56px 48px;}.gr-sec{margin-bottom:36px;}.gr-h2{font-size:0.95em;font-weight:700;color:#713f12;text-transform:uppercase;letter-spacing:2px;margin:0 0 20px;display:flex;align-items:center;gap:12px;}.gr-h2::after{content:'';flex:1;height:1px;background:#fef08a;}.gr-p{font-size:0.95em;color:#713f12;line-height:1.8;}.gr-grid{display:grid;grid-template-columns:1fr 1fr;gap:40px;}.card-side{display:none;}.work-card{margin-bottom:28px;border-left:2px solid #fef08a;padding-left:16px;}.card-header{margin-bottom:6px;}.position{font-size:1.1em;font-weight:700;color:#713f12;}.company{font-size:0.95em;color:var(--primary-color);font-weight:600;}.date{font-size:0.85em;color:#854d0e;float:right;font-weight:500;}.summary{font-size:0.95em;color:#713f12;line-height:1.7;margin-top:8px;clear:both;}.edu-card{margin-bottom:20px;}.edu-info .area{font-size:1em;font-weight:700;color:#713f12;}.edu-info .institution{font-size:0.9em;color:#854d0e;margin-top:4px;}.edu-date{font-size:0.85em;color:var(--primary-color);font-weight:600;display:block;margin-top:4px;}.gr-skills .skill-row{margin-bottom:12px;}.gr-skills .skill-meta{display:flex;justify-content:space-between;font-size:0.9em;font-weight:600;color:#713f12;margin-bottom:4px;}.gr-skills .skill-track{height:4px;background:#fef08a;border-radius:2px;}.gr-skills .skill-fill{height:100%;background:var(--primary-color);border-radius:2px;}`
  }
};

content = content.replace('};', '');
content = content + '\n';

for (const [key, val] of Object.entries(newTemplates)) {
  content += `  '${key}': { name: '${val.name}', category: '${val.category}', accent: '${val.accent}', thumbnail: '${val.thumbnail}',\n    html: \`${val.html}\`,\n    css: \`${val.css}\`\n  },\n`;
}

content += '\n};\n';

fs.writeFileSync(filePath, content, 'utf8');
console.log('Templates appended successfully.');
